In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
def randomGen(x):
    lst=[]
    for i in range(x):
        lst.append(random.randint(21,100))
    return lst

In [3]:
randomGen(7)

[96, 48, 88, 29, 61, 77, 80]

In [12]:
nums = randomGen(50)
print("List of numbers below 33: \n{}".format(pd.Series(nums)[pd.Series(nums)<33]))
print("{} numbers are below 33.".format(len(pd.Series(nums)[pd.Series(nums)<33])))

List of numbers below 33: 
7     21
9     25
14    31
18    22
31    25
34    30
39    26
dtype: int64
7 numbers are below 33.


In [13]:
numArray = np.array(pd.Series(nums))
modified = np.reshape(numArray, (5,10))
df = np.where(modified<50, modified, modified * 50)
print("Modified array 5x10: \n{}".format(modified))
print("Replaced numbers less than, equal and multiplied: \n{}".format(df))

Modified array 5x10: 
[[ 96  75  96  63  91  55  89  21  66  25]
 [ 96  56  91  78  31  38  69  45  22  37]
 [ 60  66 100  47  61  99  79  56  69  57]
 [ 60  25  57  95  30  46  63  53  80  26]
 [ 64  83  40  80  84  82  82  86  60  39]]
Replaced numbers less than, equal and multiplied: 
[[4800 3750 4800 3150 4550 2750 4450   21 3300   25]
 [4800 2800 4550 3900   31   38 3450   45   22   37]
 [3000 3300 5000   47 3050 4950 3950 2800 3450 2850]
 [3000   25 2850 4750   30   46 3150 2650 4000   26]
 [3200 4150   40 4000 4200 4100 4100 4300 3000   39]]
